[tool.black]
line-length = 100
target-version = ['py38', 'py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  | manticore
  | mui/server_utils
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

# mypy global options:
[tool.mypy]
files = ['mui', 'tests']
warn_unused_configs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
