name: binaryninja-ci
on:
  push:
    paths:
      - 'plugins/binaryninja/**'
    branches-ignore:
      - 'binja-migration/master'
  pull_request:
    paths:
      - 'plugins/binaryninja/**'
    branches-ignore:
      - 'binja-migration/master'

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 'Install tools'
        run: |
          # just command runner https://github.com/casey/just#pre-built-binaries
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "${HOME}/.local/bin"

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          custom_cache_key_element: v2

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

        # the package installation will only be executed when the
        # requirements-files have changed.
      - run: pip install -r plugins/binaryninja/requirements-dev.txt -r plugins/binaryninja/binjastub/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Lint
        run: just -d plugins/binaryninja -f plugins/binaryninja/justfile lint
